---
# tasks file for hostname
- name: hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  register: "hostname_status"
  become: true
  when: ansible_hostname != inventory_hostname_short
